### ISSUE TITLE
Restructure

### ISSUE THREAD

**Issue by drvinceknight** [11michalis11/ED-EMS-game-paper#20]
Section 1: Intro + Motivation + Major contributions + Sign posting
Section 2: Literature Review + Major contributions
Section 3: The queuing model of a single interface.
Section 4: The game theoretic problem

**Comment by drvinceknight** [comment]
Benefit: highlight theoretic contribution in Section 3 and transition from 3 to 4 is nicer.

**Comment by MichalisPanayides** [comment]
Reviewer 1 - Comment 2
Reviewer 3 - Comments 1 & 2
