### ISSUE TITLE
Address comment 5 by reviewer 3

### ISSUE THREAD

**Issue by drvinceknight** [11michalis11/ED-EMS-game-paper#25]
- Highlight modelling choice of unobservable queue (which is not necessarily unrealistic) -- there are many references that can be added.
- Highlight possibility of more complex queueing models -- good idea but outside of the scope.

**Comment by MichalisPanayides** [comment]
More complex queueing models include:
- the distance to each hospital 
- patient's priority type (i.e. routine, urgent, emergency)
